#coordinates for menu buttons
BULLDOZER = (12, 12)
LANDSCAPE = (35, 12)
DISPATCH = (58, 12)
POWER = (12, 35)
WATER = (35, 35)
BONUS = (58, 35)
ROADS = (12, 58)
RAILS = (35, 58)
PORTS = (58, 58)
RESIDENTIAL = (12, 81)
COMMERCIAL = (35, 81)
INDUSTRIAL = (58, 81)
EDUCATION = (12, 103)
HEALTH = (35, 103)
RECREATION = (58, 103)
SIGNS = (20, 136)
QUERY = (50, 136)
COUNTER = (20, 162)
CLOCK = (50, 162)
ZOOMOUT = (12, 186)
ZOOMIN = (35, 186)
CENTER = (58, 186)
MAPWINDOW = (12, 212)
GRAPHS = (35, 212)
POPULATION = (12, 231)
INDUSTRYGRPHS = (35, 231)
NEIGHBORS = (12, 250)
BUDGET = (35, 250)
LAYER_BUILDING = (19, 274)
LAYER_SIGNS = (54, 274)
LAYER_ROADTREE = (19, 289)
LAYER_ZONES = (54, 289)
LAYER_UNDERGROUND = (25, 303)
ZONE_DEMAND_MAX_LEFT = (50, 203)
ZONE_DEMAND_MAX_RIGHT = (70, 203)
ZONE_DEMAND_MIN_LEFT = (50, 260)
ZONE_DEMAND_MIN_RIGHT = (70, 260)
ZONE_DEMAND_ZERO_LEFT = (50, 232)
ZONE_DEMAND_ZERO_RIGHT = (70, 232)

class Menu:
    #menu options
    BD_DEMOLISH = 0
    BD_LEVEL = 1
    BD_RAISE = 2
    BD_LOWER = 3
    BD_DEZONE = 4
    
    def __init__(self, top, left):
        self.bulldozer = (top + BULLDOZER[0], left + BULLDOZER[1])
        self.landscape = (top + LANDSCAPE[0], left + LANDSCAPE[1])
        self.dispatch = (top + DISPATCH[0], left + DISPATCH[1])
        self.power = (top + POWER[0], left + POWER[1])
        self.water = (top + WATER[0], left + WATER[1])
        self.citybonus = (top + BONUS[0], left + BONUS[1])
        self.roads = (top + ROADS[0], left + ROADS[1])
        self.rails = (top + RAILS[0], left + RAILS[1])
        self.ports = (top + PORTS[0], left + PORTS[1])
        self.residential = (top + RESIDENTIAL[0], left + RESIDENTIAL[1])
        self.commercial = (top + COMMERCIAL[0], left + COMMERCIAL[1])
        self.industrial = (top + INDUSTRIAL[0], left + INDUSTRIAL[1])
        self.education = (top + EDUCATION[0], left + EDUCATION[1])
        self.health_safety = (top + HEALTH[0], left + HEALTH[1])
        self.recreation = (top + RECREATION[0], left + RECREATION[1])
        self.signs_posts = (top + SIGNS[0], left + SIGNS[1])
        self.query = (top + QUERY[0], left + QUERY[1])
        self.counter_clock = (top + COUNTER[0], left + COUNTER[1])
        self.clock = (top + CLOCK[0], left + CLOCK[1])
        self.zoom_out = (top + ZOOMOUT[0], left + ZOOMIN[1])
        self.zoom_in = (top + ZOOMIN[0], left + ZOOMIN[1])
        self.center = (top + CENTER[0], left + CENTER[1])
        self.map_window = (top + MAPWINDOW[0], left + MAPWINDOW[1])
        self.graphs = (top + GRAPHS[0], left + GRAPHS[1])
        self.population = (top + POPULATION[0], left + POPULATION[1])
        self.industry_graph = (top + INDUSTRYGRPHS[0], left + INDUSTRYGRPHS[1])
        self.neighbors = (top + NEIGHBORS[0], left + NEIGHBORS[1])
        self.budget = (top + BUDGET[0], left + BUDGET[1])
        self.layer_building = (top + LAYER_BUILDING[0], left + LAYER_BUILDING[1])
        self.layer_signs = (top + LAYER_SIGNS[0], left + LAYER_SIGNS[1])
        self.layer_road_tree = (top + LAYER_ROADTREE[0], left + LAYER_ROADTREE[1])
        self.layer_zones = (top + LAYER_ZONES[0], left + LAYER_ZONES[1])
        self.layer_underground = (top + LAYER_UNDERGROUND[0], left + LAYER_UNDERGROUND[1])
        # demand squares are of form: (a, b, c, d) with a = (x, y)
        # a--b
        # |  |
        # c--d
        self.zone_max_demand = ((top + ZONE_DEMAND_MAX_LEFT[0], left + ZONE_DEMAND_MAX_LEFT[1]), (top + ZONE_DEMAND_MAX_RIGHT[0], left + ZONE_DEMAND_MAX_RIGHT[1]), (top + ZONE_DEMAND_ZERO_LEFT[0], left + ZONE_DEMAND_ZERO_LEFT[1]), (top + ZONE_DEMAND_ZERO_RIGHT[0], left + ZONE_DEMAND_ZERO_LEFT[1]))
        self.zone_max_demand = ((top + ZONE_DEMAND_ZERO_LEFT[0], left + ZONE_DEMAND_ZERO_LEFT[1]), (top + ZONE_DEMAND_ZERO_RIGHT[0], left + ZONE_DEMAND_ZERO_LEFT[1]), (top + ZONE_DEMAND_MIN_LEFT[0], left + ZONE_DEMAND_MIN_LEFT[1]), (top + ZONE_DEMAND_MIN_RIGHT[0], left + ZONE_DEMAND_MIN_RIGHT[1]))        
